### ISSUE TITLE
line-breaks break italic/bold

### ISSUE THREAD

**Issue by aspiers** [thorstenb/odpdown#12]
```markdown
**This is a multi-line sentence
which should be bold.**
```

does not get rendered bold, and the `**` stay as normal text.  Same with italics etc.  In contrast this is how github renders it: 

**This is a multi-line sentence
which should be bold.**

**Comment by thorstenb** [comment]
That one looks fundamentally unsupported in mistune (block vs. inline grammar split there). I wonder if a line continuation a la '\' would fly with upstream, need to try.

**Comment by lepture** [comment]
It is not very clear whether you can or cannot render it bold with multi-lines.

**Comment by lepture** [comment]
Version 0.6 supports multi-lines now.
