### ISSUE TITLE
Allow simple formatting inside code blocks

### ISSUE THREAD

**Issue by rombert** [thorstenb/odpdown#33]
When presenting code blocks it is sometimes useful to point out a single word or line of that code block. I usually bold out the respective word/line for empahsis.

It would be useful to be able to do the same with odpdown

**Comment by thorstenb** [comment]
Any suggestion for how to do the markup there?

**Comment by rombert** [comment]
I think this should only apply to 'regular' code blocks, indented by 4 spaces, as for the pygments-managed ones it makes little sense. For my uses it is enough to allow bold, using something like

     public static final String *BOLD* = "bold";

would make the string 'BOLD' appear in bold face.

**Comment by thorstenb** [comment]
that's not trivial to specify / implement robustly - imagine code containing something like
    x = 2*alpha*beta*gamma;
the point of code blocks is precisely that its formatting is taken as-is.

I'll give this some more thoughts (and you might, too), but at it's current state, this is a wontfix for me.

**Comment by rombert** [comment]
I see the problem here . What about the possibility of adding highlighting instructions outside the text? Something like: `highlight: /public/` which would bold all occurrences of the work 'public' in the code block. 

This might work from a syntax POV with the pygment-based instructions, but I don't think we should touch those, but the default code blocks ( 4 space indent ). But I'm not sure where to attach that instruction...

**Comment by thorstenb** [comment]
Hmm, tough. And I wonder how specific to your taste this visual highlighting is. For a presentation, conceivably also having an animation effect on that particular keyword could be nice. But then the needed markup gets even more into horror-land...

Adam had another idea for having high-level meta info somehow inline in issue #4 so perhaps I would reconsider the idea within a more general context of adding highlighting/effects/visual clues to individual slides.
