### ISSUE TITLE
Master slides with underscores in names are not correctly matched

### ISSUE THREAD

**Issue by rombert** [thorstenb/odpdown#35]
I have a very simple master file with two master slides

* Master_v2
* Content_v2

Running

`odpdown --break-master Master_v2 --content-master Content_v2 input.md master_with_underscore.odp out.odp`

results in 

    Available master page names in template:
    ----------------------------------------

    For  visual  inspection,  select  View->Master->Slide  Master  in
    Impress. The names listed below are the slide names of the master
    pages you  see in the  slide preview  pane. Hover over  the slide
    thumbnails to  have them  displayed, right-click and  pick Rename
    Master to choose more speaking names.

    - Content_5f_v2
    - Master_5f_v2

**Comment by thorstenb** [comment]
Impress escapes underscores (hex 5f is the underscore), so giving the name exactly as written in the diagnostics output should work.

**Comment by rombert** [comment]
Yes, using the name from the diagnostic output works. I raised this issue because the current behaviour is unexpected - the names that odpdown uses are not the ones shown to the user in impress.

But it's definitely something I can live with :-)
