### ISSUE TITLE
List items problem ?

### ISSUE THREAD

**Issue by metal3d** [thorstenb/odpdown#38]
Another bug for me but I've got a workaround.

If I use:
```
This is a list:
- item1
- item2
- item3
```
I have no list in my slide. 

But, this works
```
- This is a list:
  - item1
  - item2
  - item3
```

Now, items are list and "This is a list" appears as a normal text. It's a workaround, but maybe you may try to see what happends.

**Comment by thorstenb** [comment]
Don't see that here. Can you stick a fully non-working .md file somewhere for me to try?

**Comment by thorstenb** [comment]
No further input, closing for the moment. If this is reproducible again, please re-open with a smallish example.
