### ISSUE TITLE
reference to invalid image corrupts output .odp

### ISSUE THREAD

**Issue by aspiers** [thorstenb/odpdown#9]
I had mistakenly included a reference to a webpage as if it was an image:

```
![Architecture diagram](http://clusterlabs.org/wiki/File:Stack.png)
```

and `odpgen` built an unusably corrupt `.odp` with no obvious sign what had gone wrong.

**Comment by thorstenb** [comment]
Seems LibreOffice does not like ':' in internal media component names. The fact that it's html is coincidental to the issue.
